name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          command_timeout: 200m
          script: |
            cd /data/www/zeepsopje.com
            git pull
            docker compose build --force-rm --no-cache --compress --build
            docker compose up -d
